제외 및 확장자 검색 옵션 추가
weirdmeetup/koalabot pull request #28
Opened 2017-08-22 11:50 UTC by Jack-Valentine

구글 검색시 gif 에 대해서 검색하는 부분 추가
특정 사이트 제외 옵션 추가
- 특정 이미지 미리보기 지원하지 않는 사이트 추가
- 불편한 요소가 있는 사이트 추가

2017-08-22 12:20 UTC, riseshia requested changes
Make test on this project way, or delete it.
Remind `scripts/` for hubot plugins, not for test

2017-08-22 23:36 UTC, riseshia commented on scripts/test.js
> +/**
Don't you remove this one?

2017-08-23 00:20 UTC, Jack-Valentine commented on scripts/test.js
> +/**
Sorry my mistake. I removed it.

2017-08-23 00:22 UTC, riseshia approved these changes

2017-08-23 00:22 UTC, merged